name: Terraform Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:
    inputs:
      region:
        description: 'Region to deploy (e.g., us-east-1)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Install Testcontainers CLI with Authentication
      - name: Install Testcontainers CLI
        run: |
          npm install -g @testcontainers/cloud-cli
          export TC_CLOUD_TOKEN=${{ secrets.TC_CLOUD_TOKEN }}  # Set token
          testcontainers --version || echo "Testcontainers CLI installation failed"

      # ✅ Set up Testcontainers Cloud Client with Debug Mode
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
          debug: true

      # ✅ Ensure the agent has enough time to start
      - name: Increase Testcontainers Cloud Timeout
        run: echo "TESTCONTAINERS_CLOUD_AGENT_TIMEOUT=300" >> $GITHUB_ENV

      # ✅ Ensure network is allowed
      - name: Allow Network for Testcontainers
        run: echo "TESTCONTAINERS_CLOUD_ALLOW_NETWORK=true" >> $GITHUB_ENV

      # ✅ Run Testcontainers Tests (Replace with your actual test command)
      - name: Run Testcontainers Tests
        run: |
          echo "Running Testcontainers-based tests..."
          # Example: ./run-tests.sh  # Replace with your actual test command
